implicit declaration of sha1_prf() Error When compiling hostapd inside the kernel build system, compilation fails with:
    hostapd-2.11/src/ap/wpa_auth.c:668:13: error:
    implicit declaration of function sha1_prf; did you mean sha512_prf?
      668 |     if (sha1_prf(rkey, sizeof(rkey), Init Counter, buf, sizeof(buf),

Userspace hostapd normally provides sha1_prf() in its crypto layer, but when ported into kernel space the symbol is not available, causing
-Werror=implicit-function-declaration to stop the build.

This commit introduces a kernel-based replacement for sha1_prf() using:
    - kernel crypto API (hmac(sha1))
    - struct shash_desc workflow

The replacement is implemented in porting/sha1_prf_fix.h.

Also added macro overrides so that hostapd uses our wrapper without modifying any hostapd .c files:

    #undef sha1_prf
    #define sha1_prf hostapd_sha1_prf

This keeps hostapd source untouched while resolving the missing prototype
and avoiding signature conflicts.