Fixing Implicit declaration of fread() Error Hostapd source expects libc fread(), which is not available in kernel space. Added fread() implementation in porting/file_ops.h that maps to kernel_read(),mirroring behavior of existing k_fopen(), k_fgets(), and k_fclose.
This resolves:
  error: implicit declaration of function 'fread'

Also defined FILE as struct file to ensure compatibility with kernel APIs.